character_movement: main.o game_loop.o
	g++ -Wall -g main.cpp game_loop.cpp -lncurses -o character_movement
	./character_movement
	rm main.o game_loop.o character_movement
	rm -rf character_movement.dSYM
